# Generated by Django 5.1.6 on 2025-02-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answers', models.JSONField()),
                ('question_type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], max_length=10)),
                ('language', models.CharField(default='fr', max_length=10)),
            ],
        ),
    ]
