# Generated by Django 5.1.6 on 2025-02-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_quiz_id_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='status',
            field=models.CharField(choices=[('passing', 'Passing'), ('good', 'Good'), ('excellent', 'Excellent'), ('zero', 'Zero')], default='passing', max_length=20),
        ),
    ]
